import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, Database, Wrench } from 'lucide-react';
import AdSlot from '@/components/ads/AdSlot';
import ManufacturerCard from '@/components/catalog/ManufacturerCard';
import { CATALOG_MANUFACTURERS, CATALOG_MODELS, CATALOG_PARTS } from '@/data/catalog';

export default function ManufacturerPage({ params }: { params: { manufacturer: string } }) {
  const manufacturer = CATALOG_MANUFACTURERS.find((item) => item.id === params.manufacturer);
  if (!manufacturer) notFound();
  const models = CATALOG_MODELS.filter((model) => model.manufacturerId === manufacturer.id);
  const parts = CATALOG_PARTS.filter((part) => part.specifications?.manufacturerId === manufacturer.id);
  return <main className="min-h-screen bg-gray-50"><section className="max-w-7xl mx-auto px-4 py-8"><Link href="/trucks" className="inline-flex items-center gap-2 text-blue-600 hover:text-blue-800 mb-8"><ArrowLeft size={18} /> Back to manufacturers</Link><div className="bg-white rounded-xl border border-gray-200 p-8 mb-8"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-5"><div><p className="text-sm font-semibold text-blue-600 uppercase tracking-wide">Manufacturer catalogue</p><h1 className="text-4xl font-bold text-gray-900 mt-1">{manufacturer.name}</h1><p className="text-gray-600 mt-2">Models and part templates currently indexed for search.</p></div><div className="flex gap-3 text-sm"><div className="rounded-lg bg-gray-50 border px-4 py-3"><strong>{models.length}</strong><span className="ml-1 text-gray-500">models</span></div><div className="rounded-lg bg-gray-50 border px-4 py-3"><strong>{parts.length}</strong><span className="ml-1 text-gray-500">part records</span></div></div></div></div><AdSlot placement="manufacturer-top" /><section className="mt-10"><h2 className="text-2xl font-bold text-gray-900 mb-6">Models</h2><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">{models.map((model) => <div key={model.id} className="bg-white rounded-xl border p-5"><div className="flex items-center gap-2 text-blue-600 mb-3"><Database size={18} /><span className="text-xs font-semibold uppercase">Model</span></div><h3 className="font-semibold text-lg text-gray-900">{model.name}</h3></div>)}</div></section><section className="mt-10"><h2 className="text-2xl font-bold text-gray-900 mb-6">Part systems</h2><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">{Array.from(new Set(parts.map((part) => part.category))).map((category) => <div key={category} className="bg-white rounded-xl border p-4"><Wrench size={18} className="text-gray-500 mb-2" /><p className="font-medium text-gray-900">{category}</p></div>)}</div></section><section className="mt-10 bg-white rounded-xl border p-6"><h2 className="text-xl font-bold text-gray-900 mb-3">Data quality</h2><p className="text-gray-600 text-sm leading-6">OEM references marked as source-listed are discoverability data, not proof of exact vehicle fitment. Always confirm the exact model, generation, engine, axle/chassis and VIN where required in the manufacturer catalogue before ordering.</p><div className="mt-5"><ManufacturerCard manufacturer={{ ...manufacturer, modelCount: models.length, partCount: parts.length }} /></div></section></section></main>;
}
